export const WEBINARS = [
  {
    slug: 'cybersecurity-2025-pakistan',
    title: 'Cybersecurity in 2025: What Pakistani Businesses Need to Know',
    date: 'January 2025',
    duration: '48 min',
    color: '#DC2626',
    bg: '#FEF2F2',
    desc: 'Our security team walks through the most significant threats targeting Pakistan businesses in 2025 — ransomware, BEC fraud, supply-chain attacks — with practical defensive measures for each.',
    topics: [
      'Top 5 ransomware attack patterns targeting Pakistan businesses in 2025',
      'Business Email Compromise (BEC) fraud — real cases and prevention',
      'Supply-chain attacks: how vendors become your biggest risk',
      'Building a cyber incident response plan in under 30 days',
      'Free security tools every SMB should be running today',
    ],
    takeaways: [
      'Know which attack types are rising fastest in Pakistan',
      'A 10-point security checklist you can action immediately',
      'How to evaluate your current security posture honestly',
      'What a real incident response looks like — step by step',
    ],
  },
  {
    slug: 'microsoft-365-security-beyond-defaults',
    title: 'Microsoft 365 Security: Beyond Default Settings',
    date: 'February 2025',
    duration: '52 min',
    color: '#0078D4',
    bg: '#EFF6FF',
    desc: 'A technical deep-dive into the security configurations that M365 does not enable by default — Conditional Access, MFA enforcement, Defender for Office 365, and Purview compliance tools.',
    topics: [
      'Why M365 default settings leave you exposed — and what to change first',
      'Conditional Access policies: blocking risky sign-ins without frustrating users',
      'Microsoft Defender for Office 365: P1 vs P2 and what you actually need',
      'MFA enforcement strategies that get user buy-in',
      'Purview compliance and eDiscovery for regulated industries',
    ],
    takeaways: [
      'A prioritised list of M365 security settings to enable this week',
      'Conditional Access policy templates ready to deploy',
      'How to read Secure Score and what to target first',
      'Common M365 misconfigurations and how to find them in your tenant',
    ],
  },
  {
    slug: 'ai-automation-finance-teams',
    title: 'AI Automation for Finance Teams: Real Examples',
    date: 'March 2025',
    duration: '45 min',
    color: '#D97706',
    bg: '#FFFBEB',
    desc: 'Live demonstrations of AI automation applied to accounts payable processing, financial reporting, and treasury reconciliation — with real before/after time metrics from Pakistan businesses.',
    topics: [
      'Accounts payable automation: invoice capture, matching, and approval workflows',
      'Financial reporting: automated data aggregation and dashboard generation',
      'Treasury reconciliation: reducing manual effort by 80%',
      'Build vs buy: when to use Power Automate, n8n, or custom AI solutions',
      'ROI calculation framework for your first automation project',
    ],
    takeaways: [
      'Three automation projects you can start next week with no coding',
      'How to calculate ROI before you build anything',
      'Which repetitive finance tasks are best suited for AI automation',
      'Real time savings from Pakistan businesses that have made the shift',
    ],
  },
]
