export const CATEGORIES = [
  { label: 'All',               slug: null,               color: '#071a37' },
  { label: 'Cybersecurity',     slug: 'cybersecurity',     color: '#DC2626' },
  { label: 'Cloud',             slug: 'cloud',             color: '#0078D4' },
  { label: 'AI',                slug: 'ai',                color: '#7C3AED' },
  { label: 'Networking',        slug: 'networking',        color: '#0891B2' },
  { label: 'Training',          slug: 'training',          color: '#16A34A' },
  { label: 'Managed IT',        slug: 'managed-it',        color: '#2563EB' },
  { label: 'Software',          slug: 'software',          color: '#D97706' },
  { label: 'Case Study',        slug: 'case-study',        color: '#00C853' },
  { label: 'Physical Security', slug: 'physical-security', color: '#D97706' },
]

export const POSTS = [
  {
    title: 'Why 94% of Cyberattacks Start with Email',
    excerpt: 'Email remains the single most exploited attack vector — phishing, BEC, and malware delivery all begin in the inbox. Here is what modern email security actually looks like and why most businesses are still vulnerable.',
    category: 'Cybersecurity',
    categoryColor: '#DC2626',
    date: '12 Jun 2026',
    readTime: '5 min read',
    gradientFrom: '#FEF2F2',
    gradientTo: '#DC262615',
    accentColor: '#DC2626',
    href: '/blog/why-email-is-top-cyber-threat',
  },
  {
    title: 'Microsoft 365 vs Google Workspace: Which Is Right for Your Business?',
    excerpt: 'Both platforms dominate the modern workplace conversation. We compare them honestly — email, collaboration, security, cost, and Pakistan-specific support considerations — so you can make the right choice for your organisation.',
    category: 'Cloud',
    categoryColor: '#0078D4',
    date: '5 Jun 2026',
    readTime: '7 min read',
    gradientFrom: '#EFF6FF',
    gradientTo: '#0078D415',
    accentColor: '#0078D4',
    href: '/blog/microsoft-365-vs-google-workspace',
  },
  {
    title: 'The True Cost of IT Downtime for Pakistani Businesses',
    excerpt: 'Most organisations dramatically underestimate what an IT outage actually costs. We break down the direct and indirect costs with real data — and show what proactive IT management actually saves.',
    category: 'Managed IT',
    categoryColor: '#2563EB',
    date: '28 May 2026',
    readTime: '6 min read',
    gradientFrom: '#EFF6FF',
    gradientTo: '#2563EB15',
    accentColor: '#2563EB',
    href: '/blog/true-cost-it-downtime-pakistan',
  },
  {
    title: 'What Is SOC as a Service and Does Your Business Need It?',
    excerpt: 'A Security Operations Centre was once only accessible to large enterprises. SOCaaS has changed that. We explain what it covers, what it costs, and which organisations genuinely benefit from 24/7 security monitoring.',
    category: 'Cybersecurity',
    categoryColor: '#DC2626',
    date: '20 May 2026',
    readTime: '8 min read',
    gradientFrom: '#FEF2F2',
    gradientTo: '#DC262615',
    accentColor: '#DC2626',
    href: '/blog/soc-as-a-service-explained',
  },
  {
    title: 'SD-WAN vs MPLS: The WAN Decision Every Multi-Branch Business Must Make',
    excerpt: 'MPLS has been the enterprise WAN standard for 20 years. SD-WAN is challenging it on cost, flexibility, and cloud performance. We explain the real trade-offs for organisations with multiple offices across Pakistan.',
    category: 'Networking',
    categoryColor: '#0891B2',
    date: '14 May 2026',
    readTime: '9 min read',
    gradientFrom: '#ECFEFF',
    gradientTo: '#0891B215',
    accentColor: '#0891B2',
    href: '/blog/sdwan-vs-mpls-wan-decision',
  },
  {
    title: 'How to Pass the AWS Solutions Architect Exam in 8 Weeks',
    excerpt: 'The SAA-C03 is achievable with the right study plan. We share the exact week-by-week study programme our engineers use — resources, practice exams, and the topic areas that carry the most exam weight.',
    category: 'Training',
    categoryColor: '#16A34A',
    date: '7 May 2026',
    readTime: '10 min read',
    gradientFrom: '#F0FDF4',
    gradientTo: '#16A34A15',
    accentColor: '#16A34A',
    href: '/blog/aws-solutions-architect-exam-guide',
  },
  {
    title: 'Azure vs AWS: Which Cloud Platform Should You Choose in 2025?',
    excerpt: 'The two largest cloud platforms have distinct strengths. We compare them across compute, pricing, support quality, Pakistan availability zones, and the Microsoft ecosystem integration question that decides most enterprise choices.',
    category: 'Cloud',
    categoryColor: '#0078D4',
    date: '29 Apr 2026',
    readTime: '8 min read',
    gradientFrom: '#EFF6FF',
    gradientTo: '#0078D415',
    accentColor: '#0078D4',
    href: '/blog/azure-vs-aws-cloud-comparison',
  },
  {
    title: 'RPA vs AI Automation: Understanding the Difference',
    excerpt: 'Robotic Process Automation and AI automation are frequently confused — but they solve fundamentally different problems. Here is how to decide which technology is right for the business process you want to automate.',
    category: 'AI',
    categoryColor: '#7C3AED',
    date: '22 Apr 2026',
    readTime: '6 min read',
    gradientFrom: '#F5F3FF',
    gradientTo: '#7C3AED15',
    accentColor: '#7C3AED',
    href: '/blog/rpa-vs-ai-automation-difference',
  },
  {
    title: 'CCTV vs IP Surveillance: Why IP Wins Every Time',
    excerpt: 'Analogue CCTV systems are still being installed in 2025. We explain why this is a mistake — and what modern IP surveillance delivers in image quality, remote access, analytics, and integration that analogue simply cannot.',
    category: 'Physical Security',
    categoryColor: '#D97706',
    date: '15 Apr 2026',
    readTime: '5 min read',
    gradientFrom: '#FFFBEB',
    gradientTo: '#D9770615',
    accentColor: '#D97706',
    href: '/blog/cctv-vs-ip-surveillance',
  },
  {
    title: 'ISO 27001 Certification: A Step-by-Step Guide for Pakistan Businesses',
    excerpt: 'ISO 27001 is increasingly required by enterprise clients, financial sector partners, and government contracts. We break down the certification journey — scoping, controls, risk assessment, audit, and what it actually costs.',
    category: 'Cybersecurity',
    categoryColor: '#DC2626',
    date: '8 Apr 2026',
    readTime: '11 min read',
    gradientFrom: '#FEF2F2',
    gradientTo: '#DC262615',
    accentColor: '#DC2626',
    href: '/blog/iso-27001-certification-guide-pakistan',
  },
  {
    title: 'How Infraspine Helped a Karachi Manufacturer Reduce IT Downtime by 80%',
    excerpt: 'A Karachi-based manufacturing company was losing production time to frequent server outages and ad-hoc IT support. Here is how we transformed their IT operations with managed monitoring, structured helpdesk, and proactive patching.',
    category: 'Case Study',
    categoryColor: '#00C853',
    date: '1 Apr 2026',
    readTime: '6 min read',
    gradientFrom: '#F0FDF4',
    gradientTo: '#00C85315',
    accentColor: '#00C853',
    href: '/blog/infraspine-manufacturer-downtime-case-study',
  },
  {
    title: 'The Business Case for Custom ERP vs Off-the-Shelf Software',
    excerpt: 'SAP and Oracle are not built for Pakistani businesses. We analyse the real cost comparison — implementation, licensing, customisation, and total ownership — and explain when custom ERP delivers a better return.',
    category: 'Software',
    categoryColor: '#D97706',
    date: '24 Mar 2026',
    readTime: '8 min read',
    gradientFrom: '#FFFBEB',
    gradientTo: '#D9770615',
    accentColor: '#D97706',
    href: '/blog/custom-erp-vs-off-the-shelf',
  },
]
